version: "3.9"

services:
  database:
    restart: always
    image: postgres:15.3-alpine3.18
    container_name: trackerdb
    ports:
      - "5445:5432"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    restart: always
    build: .
    container_name: server
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
      - celery
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate  --noinput &&
      python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.0.12-alpine
    container_name: cache
    command: redis-server --maxmemory-policy volatile-ttl
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=250

  celery:
    build: .
    container_name: celery
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    command: celery -A config worker --loglevel=info

  flower:
    build:
      context: .
    env_file:
      - ./.env
    container_name: flower
    command: celery -A config flower
    depends_on:
      - redis
      - celery
      - database
      - server
    ports:
      - 5555:5555
  
volumes:
  db-data: